### ISSUE TITLE
Retrieving errors on UI when events are pushed

### ISSUE THREAD

**Issue by michahirsch** [eclipse/hawkbit#556] opened 2017-07-06 05:37 UTC
It sometimes happen when using the device-simulator that the hawkBit update-server UI is throwing these errors `The operation cannot be fulfilled due to LamdaConversionException. Please contact administrator` while events get pushed cause of the device-simulator.

The following stacktrace occurs:
```
java.lang.invoke.LambdaConversionException: Type mismatch for lambda argument 0: class java.lang.Object is not convertible to interface org.eclipse.hawkbit.repository.event.TenantAwareEvent
at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:267) ~[na:1.8.0_91]
at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303) ~[na:1.8.0_91]
at java.lang.invoke.CallSite.makeSite(CallSite.java:302) ~[na:1.8.0_91]
at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307) ~[na:1.8.0_91]
at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297) ~[na:1.8.0_91]
at org.eclipse.hawkbit.ui.components.AbstractNotificationView.onEventContainerEvent(AbstractNotificationView.java:74) ~[classes/:na]
at sun.reflect.GeneratedMethodAccessor343.invoke(Unknown Source) ~[na:na]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
at org.vaadin.spring.events.internal.MethodListenerWrapper.publish(MethodListenerWrapper.java:80) ~[vaadin-spring-addon-eventbus-0.0.6.RELEASE.jar:na]
at org.vaadin.spring.events.internal.ListenerCollection.publish(ListenerCollection.java:137) ~[vaadin-spring-addon-eventbus-0.0.6.RELEASE.jar:na]
at org.vaadin.spring.events.internal.ScopedEventBus.publish(ScopedEventBus.java:109) ~[vaadin-spring-addon-eventbus-0.0.6.RELEASE.jar:na]
at org.vaadin.spring.events.internal.ScopedEventBus.publish(ScopedEventBus.java:103) ~[vaadin-spring-addon-eventbus-0.0.6.RELEASE.jar:na]
at org.eclipse.hawkbit.ui.push.DelayedEventBusPushStrategy$DispatchRunnable.lambda$1(DelayedEventBusPushStrategy.java:206) [classes/:na]
at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_91]
at org.eclipse.hawkbit.ui.push.DelayedEventBusPushStrategy$DispatchRunnable.lambda$0(DelayedEventBusPushStrategy.java:206) [classes/:na]
at com.vaadin.ui.UI.accessSynchronously(UI.java:1392) [vaadin-server-7.7.9.jar:7.7.9]
at com.vaadin.ui.UI$4.run(UI.java:1458) ~[vaadin-server-7.7.9.jar:7.7.9]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
at com.vaadin.server.VaadinService.runPendingAccessTasks(VaadinService.java:1846) [vaadin-server-7.7.9.jar:7.7.9]
at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:992) [vaadin-server-7.7.9.jar:7.7.9]
at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1809) [vaadin-server-7.7.9.jar:7.7.9]
at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1775) [vaadin-server-7.7.9.jar:7.7.9]
at com.vaadin.server.VaadinSession.access(VaadinSession.java:1384) [vaadin-server-7.7.9.jar:7.7.9]
at com.vaadin.ui.UI.access(UI.java:1455) [vaadin-server-7.7.9.jar:7.7.9]
at org.eclipse.hawkbit.ui.push.DelayedEventBusPushStrategy$DispatchRunnable.doDispatch(DelayedEventBusPushStrategy.java:201) [classes/:na]
at org.eclipse.hawkbit.ui.push.DelayedEventBusPushStrategy$DispatchRunnable.run(DelayedEventBusPushStrategy.java:159) [classes/:na]
at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:83) [spring-security-core-4.1.4.RELEASE.jar:4.1.4.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_91]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_91]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

**Comment by Yaima** [comment] 2017-07-10 19:24
<img width="1674" alt="screen shot 2017-07-10 at 12 00 46 pm" src="https://user-images.githubusercontent.com/1240271/28035759-9c68d9f4-656a-11e7-9575-76029f1b3e74.png">

**Comment by Yaima** [comment] 2017-07-10 19:27
Additional stack trace for the error: 
```2017-07-10 12:00:16.382  WARN 35535 --- [executor-pool-2] o.e.h.u.p.DelayedEventBusPushStrategy    : Wait for Vaadin session for UI 1 interrupted!

java.util.concurrent.ExecutionException: java.lang.RuntimeException: A checked exception occurred while invoking listener method onEventContainerEvent
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) [na:1.8.0_91]
	at com.vaadin.server.VaadinSession$FutureAccess.get(VaadinSession.java:124) ~[vaadin-server-7.7.9.jar:7.7.9]
	at com.vaadin.server.VaadinSession$FutureAccess.get(VaadinSession.java:85) ~[vaadin-server-7.7.9.jar:7.7.9]
	at org.eclipse.hawkbit.ui.push.DelayedEventBusPushStrategy$DispatchRunnable.doDispatch(DelayedEventBusPushStrategy.java:208) [classes/:na]
	at org.eclipse.hawkbit.ui.push.DelayedEventBusPushStrategy$DispatchRunnable.run(DelayedEventBusPushStrategy.java:159) [classes/:na]
	at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:83) [spring-security-core-4.1.4.RELEASE.jar:4.1.4.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: java.lang.RuntimeException: A checked exception occurred while invoking listener method onEventContainerEvent
	at org.vaadin.spring.events.internal.MethodListenerWrapper.publish(MethodListenerWrapper.java:91) ~[vaadin-spring-addon-eventbus-0.0.6.RELEASE.jar:na]
	at org.vaadin.spring.events.internal.ListenerCollection.publish(ListenerCollection.java:137) ~[vaadin-spring-addon-eventbus-0.0.6.RELEASE.jar:na]
	at org.vaadin.spring.events.internal.ScopedEventBus.publish(ScopedEventBus.java:109) ~[vaadin-spring-addon-eventbus-0.0.6.RELEASE.jar:na]
	at org.vaadin.spring.events.internal.ScopedEventBus.publish(ScopedEventBus.java:103) ~[vaadin-spring-addon-eventbus-0.0.6.RELEASE.jar:na]
	at org.eclipse.hawkbit.ui.push.DelayedEventBusPushStrategy$DispatchRunnable.lambda$1(DelayedEventBusPushStrategy.java:206) [classes/:na]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_91]
	at org.eclipse.hawkbit.ui.push.DelayedEventBusPushStrategy$DispatchRunnable.lambda$0(DelayedEventBusPushStrategy.java:206) [classes/:na]
	at com.vaadin.ui.UI.accessSynchronously(UI.java:1392) ~[vaadin-server-7.7.9.jar:7.7.9]
	at com.vaadin.ui.UI$4.run(UI.java:1458) ~[vaadin-server-7.7.9.jar:7.7.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
	at com.vaadin.server.VaadinService.runPendingAccessTasks(VaadinService.java:1846) ~[vaadin-server-7.7.9.jar:7.7.9]
	at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:992) ~[vaadin-server-7.7.9.jar:7.7.9]
	at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1809) ~[vaadin-server-7.7.9.jar:7.7.9]
	at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1775) ~[vaadin-server-7.7.9.jar:7.7.9]
	at com.vaadin.server.VaadinSession.access(VaadinSession.java:1384) ~[vaadin-server-7.7.9.jar:7.7.9]
	at com.vaadin.ui.UI.access(UI.java:1455) ~[vaadin-server-7.7.9.jar:7.7.9]
	at org.eclipse.hawkbit.ui.push.DelayedEventBusPushStrategy$DispatchRunnable.doDispatch(DelayedEventBusPushStrategy.java:201) [classes/:na]
	... 9 common frames omitted
Caused by: java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341) ~[na:1.8.0_91]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307) ~[na:1.8.0_91]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297) ~[na:1.8.0_91]
	at org.eclipse.hawkbit.ui.components.AbstractNotificationView.onEventContainerEvent(AbstractNotificationView.java:74) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.vaadin.spring.events.internal.MethodListenerWrapper.publish(MethodListenerWrapper.java:80) ~[vaadin-spring-addon-eventbus-0.0.6.RELEASE.jar:na]
	... 26 common frames omitted
Caused by: java.lang.invoke.LambdaConversionException: Type mismatch for lambda argument 0: class java.lang.Object is not convertible to interface org.eclipse.hawkbit.repository.event.TenantAwareEvent
	at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:267) ~[na:1.8.0_91]
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303) ~[na:1.8.0_91]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302) ~[na:1.8.0_91]
	... 34 common frames omitted```

**Comment by michahirsch** [comment] 2017-07-11 07:31
@Yaima thanks for providing additional information!

**Comment by schabdo** [comment] 2018-10-22 13:40
I close this issue for now since I see no chance to reproduce it. Please feel free to reopen it if you'll be able to reproduce it.

**Closed by schabdo** 2018-10-22 13:40 UTC
Labels: bug, cannot reproduce
