### ISSUE TITLE
Setup Hawkbit for testing with SWUpdate

### ISSUE THREAD

**Issue by sbabic** [eclipse/hawkbit#256] opened 2016-07-22 10:29 UTC
Hi everybody, 

I I would like to set up a test environment with HawkBit and SWUpdate to better test recent inclusion of patches to connect SWUpdate to Hawkbit. I started on a fresh installed Ubuntu-16.04 with the requirements as in your guide, adjusting application.properties for the example-app as suggested in your guide. I just create an empty database before running hawkbit. I see that this is recognized by hawkbit and it starts a migration - that fails. The log is :

Migration V1_0_1__init___MYSQL.sql failed
-----------------------------------------
SQL State  : 42000
Error Code : 1071
Message    : Specified key was too long; max key length is 767 bytes
Query is :     create index sp_idx_target_info_02 on sp_target_info (target_id, update_status)
Location   : db/migration/MYSQL/V1_0_1__init___MYSQL.sql (/home/stefano/Projects/hawkbit/file:/home/stefano/Projects/hawkbit/examples/hawkbit-example-app/target/hawkbit-example-app-0.2.0-SNAPSHOT.jar!/lib/hawkbit-repository-jpa-0.2.0-SNAPSHOT.jar!/db/migration/MYSQL/V1_0_1__init___MYSQL.sql)
Line       : 361
Statement  :     create index sp_idx_target_info_02 on sp_target_info (target_id, update_status)

	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:634)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:444)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1117)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1012)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 65 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Migration V1_0_1__init___MYSQL.sql failed
-----------------------------------------
SQL State  : 42000
Error Code : 1071
Message    : Specified key was too long; max key length is 767 bytes
Query is :     create index sp_idx_target_info_02 on sp_target_info (target_id, update_status)
Location   : db/migration/MYSQL/V1_0_1__init___MYSQL.sql (/home/stefano/Projects/hawkbit/file:/home/stefano/Projects/hawkbit/examples/hawkbit-example-app/target/hawkbit-example-app-0.2.0-SNAPSHOT.jar!/lib/hawkbit-repository-jpa-0.2.0-SNAPSHOT.jar!/db/migration/MYSQL/V1_0_1__init___MYSQL.sql)
Line       : 361
Statement  :     create index sp_idx_target_info_02 on sp_target_info (target_id, update_status)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1572)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 80 more
Caused by: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Migration V1_0_1__init___MYSQL.sql failed
-----------------------------------------
SQL State  : 42000
Error Code : 1071
Message    : Specified key was too long; max key length is 767 bytes
Query is :     create index sp_idx_target_info_02 on sp_target_info (target_id, update_status)
Location   : db/migration/MYSQL/V1_0_1__init___MYSQL.sql (/home/stefano/Projects/hawkbit/file:/home/stefano/Projects/hawkbit/examples/hawkbit-example-app/target/hawkbit-example-app-0.2.0-SNAPSHOT.jar!/lib/hawkbit-repository-jpa-0.2.0-SNAPSHOT.jar!/db/migration/MYSQL/V1_0_1__init___MYSQL.sql)
Line       : 361
Statement  :     create index sp_idx_target_info_02 on sp_target_info (target_id, update_status)

	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:117)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:71)
	at org.flywaydb.core.internal.command.DbMigrate$5.doInTransaction(DbMigrate.java:287)
	at org.flywaydb.core.internal.command.DbMigrate$5.doInTransaction(DbMigrate.java:285)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:285)
	at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:46)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:207)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:972)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:919)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1320)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:919)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1700)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1639)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1568)
	... 89 more
Caused by: java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
Query is :     create index sp_idx_target_info_02 on sp_target_info (target_id, update_status)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:250)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:278)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:291)
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.executeStatement(JdbcTemplate.java:238)
	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:114)
	... 110 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Specified key was too long; max key length is 767 bytes
Query is :     create index sp_idx_target_info_02 on sp_target_info (target_id, update_status)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:908)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:574)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:269)

I see that the schema is partially created before the error - anyway, a key longer as 767 bytes, as the error message says, looks improbable.

If I restart the example-app, I get another error - but this is plausible with a partially set schema. Dropping all tables, I can reproduce the error with the "Specified key was too long; max key length is 767 bytes".

Any hints ?

Thanks,
Stefano Babic

**Comment by michahirsch** [comment] 2016-07-22 11:14
Hi @sbabic 

what's your MySql version? 
You can retrieve your version by executing
```
SHOW GLOBAL VARIABLES LIKE '%version%';

| Variable_name    |   Value    |
| innodb_version   |	 5.6.26 |
| protocol_version | 	  10    |
```

The MySql documentation documents this limitation:
http://dev.mysql.com/doc/refman/5.6/en/innodb-restrictions.html
> By default, an index key for a single-column index can be up to 767 bytes. The same length limit applies to any index key prefix. See Section 13.1.13, “CREATE INDEX Syntax”. For example, you might hit this limit with a column prefix index of more than 255 characters on a TEXT or VARCHAR column, assuming a UTF-8 character set and the maximum of 3 bytes for each character. When the innodb_large_prefix configuration option is enabled, this length limit is raised to 3072 bytes, for InnoDB tables that use the DYNAMIC and COMPRESSED row formats.

We are using MySql on local machine and testing environments using mysql-docker container and works fine. On my local mysql instance is the configuration `innodb_large_prefix` not enabled.

**Comment by sbabic** [comment] 2016-07-22 12:01
Hi Michael,

On 22/07/2016 13:14, Michael Hirsch wrote:
> Hi @sbabic <https://github.com/sbabic>
> 
> what's your MySql version?
> You can retrieve your version by executing
> 
> |SHOW GLOBAL VARIABLES LIKE '%version%'; | Variable_name | Value | |
> innodb_version | 5.6.26 | | protocol_version | 10 | |
> 

MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE '%version%';
+-------------------------+----------------------------------+
| Variable_name           | Value                            |
+-------------------------+----------------------------------+
| innodb_version          | 5.6.29-76.2                      |
| protocol_version        | 10                               |
| slave_type_conversions  |                                  |
| version                 | 10.0.25-MariaDB-0ubuntu0.16.04.1 |
| version_comment         | Ubuntu 16.04                     |
| version_compile_machine | x86_64                           |
| version_compile_os      | debian-linux-gnu                 |
| version_malloc_library  | bundled jemalloc                 |
+-------------------------+----------------------------------+


> The MySql documentation documents this limitation:
> http://dev.mysql.com/doc/refman/5.6/en/innodb-restrictions.html
> 
>     By default, an index key for a single-column index can be up to 767
>     bytes. The same length limit applies to any index key prefix. See
>     Section 13.1.13, “CREATE INDEX Syntax”. For example, you might hit
>     this limit with a column prefix index of more than 255 characters on
>     a TEXT or VARCHAR column, assuming a UTF-8 character set and the
>     maximum of 3 bytes for each character. When the innodb_large_prefix
>     configuration option is enabled, this length limit is raised to 3072
>     bytes, for InnoDB tables that use the DYNAMIC and COMPRESSED row
>     formats.
> 

The question is then what happens with MAria-DB using Xtradb engine
instead of Innodb...

Anyway, it looks to me quite strange that an idex should be so large, it
points to me to some other kind of problem.

> We are using MySql on local machine and testing environments using
> mysql-docker container and works fine.

But are you using mysql or mariadb ? The guide points explicitely to
maria-db.

> On my local mysql instance is the
> configuration |innodb_large_prefix| not enabled.

ok - let's see if there are some other mismatch. Do you run on some
recent distro like Ubuntu 16.04 as I have ? Some issue about the JVM ?

I have:

stefano@patito:~$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Is there some mysql script to setup the DB, as usual with mysql ?
Something I can call like "mysql -u root <database> < initdb.sql" ?

Regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by michahirsch** [comment] 2016-07-22 13:44
You are right, I think that's a problem because this is a combined index of the `target_id` and `updateStatus`. The `target_id` is a `bigint` which uses `4 bytes` and the `updateStatus` is using a `varchar` of a length of `255` which in case of `utf8` it could take up to 3 bytes per character which would then `3 * 255 = 765 bytes`

I guess the problem is that the combined index is using the `8bytes + 765bytes = 773bytes` which is greater than `767 bytes`. I'm not sure why this didn't happened before when others were using hawkBit. 

We need to fix this by reducing the length of the `updateStatus` column because this column does not need a length of 255 characters. This column be reduced to I guess around 64 characters or even less.


> Is there some mysql script to setup the DB, as usual with mysql ?
Something I can call like "mysql -u root <database> < initdb.sql" ?

Sorry there is no script like this, because hawkBit is using ![Flyway](https://flywaydb.org/) for database migration and manual initialization and migration combined with flyway is not that good.

**Comment by sbabic** [comment] 2016-07-22 13:53
Hi Michael,

On 22/07/2016 15:44, Michael Hirsch wrote:
> You are right, I think that's a problem because this is a combined index
> of the |target_id| and |updateStatus|. The |target_id| is a |bigint|
> which uses |4 bytes| and the |updateStatus| is using a |varchar| of a
> length of |255| which in case of |utf8| it could take up to 3 bytes per
> character which would then |3 * 255 = 765 bytes|
> 
> I guess the problem is that the combined index is using the |8bytes +
> 765bytes = 773bytes| which is greater than |767 bytes|. I'm not sure why
> this didn't happened before when others were using hawkBit.
> 

You needed a new tester ;-)

> We need to fix this by reducing the length of the |updateStatus| column
> because this column does not need a length of 255 characters. This
> column be reduced to I guess around 64 characters or even less.
> 
>     Is there some mysql script to setup the DB, as usual with mysql ?
>     Something I can call like "mysql -u root < initdb.sql" ?
> 
> Sorry there is no script like this, because hawkBit is using Flyway
> <https://camo.githubusercontent.com/22442f1da01807bb76721f46a427ff4dd21fe9b9/68747470733a2f2f666c7977617964622e6f72672f>
> for database migration and manual initialization and migration combined
> with flyway is not that good.

Understood, thanks.

Regards,
Stefano


-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by michahirsch** [comment] 2016-07-22 14:08
> You needed a new tester ;-)
Do you want the job? :) :+1: 

I've pushed a branch with the necessary flyway migration script to reduce the column length of `updateStatus` maybe you can try out the branch? 
https://github.com/bsinno/hawkbit/tree/fix_index_sp_idx_target_info_02_too_long

Thanks,
Michael

**Comment by sbabic** [comment] 2016-07-22 17:31
Hi Michael,

On 22/07/2016 16:08, Michael Hirsch wrote:
>     You needed a new tester ;-)
>     Do you want the job? :) 👍
> 

I have to be a tester anyway if I want to test my stuff ;-)

> I've pushed a branch with the necessary flyway migration script to
> reduce the column length of |updateStatus| maybe you can try out the
> branch?
> https://github.com/bsinno/hawkbit/tree/fix_index_sp_idx_target_info_02_too_long
> 

It does not help - I get the same issue.

However, in my log I see:

"Migrating schema `hawkbit` to version 1.0.1" - that means the init db.
You have fixed the last migration, my startup blocks at the early beginning.

Regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by michahirsch** [comment] 2016-07-22 18:38
@sbabic  Thanks for testing :+1: , yeah that's true, problem is that I cannot change the initial migration script due I would change it and flyway will complain about checksum mismatch. I'll need to figure it out how to change it without modifying the existing mysql script.

Need to setup an MySql which also fails with this error. 

Thanks,
Michael

**Comment by sbabic** [comment] 2016-07-27 16:27
Hi Michael,

On 22/07/2016 20:38, Michael Hirsch wrote:
> @sbabic <https://github.com/sbabic> Thanks for testing 👍 , yeah that's
> true, problem is that I cannot change the initial migration script due I
> would change it and flyway will complain about checksum mismatch. I'll
> need to figure it out how to change it without modifying the existing
> mysql script.
> 
> Need to setup an MySql which also fails with this error.
> 

It is worth maybe to mention somewhere (guide ?) a workaround.

mariadb in current distros (tested on Ubuntu 16.04) is set with:

character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci

It is enough to set the collation for the hawkbit's database to reduce
the number of bytes per character. I set collation to "latin1_bin" (1
byte x character), and the whole migration works up to the end.

Best regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by michahirsch** [comment] 2016-07-28 06:58
HI @sbabic ,

thanks for the workaround, yeah the utf8mb4 is can use up to 4 bytes. I've just checked my lokal MySql instance and I'm using the `utf8` characterset.

Thanks for the hint :+1: 

Nevertheless the combinded index of `target_id` and `updateStatus` should be reduced, but not sure if this is working in the initial script, because as I said it will causes checksum check problems on flyway.

Thanks,
Michael

**Comment by sbabic** [comment] 2016-07-28 07:00
Hi Michael,

On 28/07/2016 08:58, Michael Hirsch wrote:
> HI @sbabic <https://github.com/sbabic> ,
> 
> thanks for the workaround, yeah the utf8mb4 is can use up to 4 bytes.
> I've just checked my lokal MySql instance and I'm using the |utf8|
> characterset.
> 
> Thanks for the hint 👍
> 
> Nevertheless the combinded index of |target_id| and |updateStatus|
> should be reduced, but not sure if this is working in the initial
> script, because as I said it will causes checksum check problems on flyway.

I does not work by simply reducing the field - I have tried, I got
another error.

Regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by kaizimmerm** [comment] 2016-10-15 05:35
I wil close this for now. There is actually not much we can do as a change on the original script will cause problems for existing installations.

**Closed by kaizimmerm** 2016-10-15 05:35 UTC
Labels: bug
