### ISSUE TITLE
DDI API: The config URL should be always available 

### ISSUE THREAD

**Issue by EugenWiens** [eclipse/hawkbit#389] opened 2016-12-12 07:33 UTC
Hi,
It will be grade if the configuration URL (configData) will be available on every request on the "Base Poll Resource". It is possible that the configuration is changing e.g. after update, booting to recovery mode, ...
If the target will report a new config it must save the config URL and that is not so easy. If the configuration URL is available on every request to the "Base Poll Resource" the target can decide if the configuration has changed an report if necessary.

**Comment by sbabic** [comment] 2016-12-19 10:00
Hi Eugen,

On 12/12/2016 08:33, Eugen Wiens wrote:
> Hi,
> It will be grade if the configuration URL (configData) will be available
> on every request on the "Base Poll Resource". It is possible that the
> configuration is changing e.g. after update, booting to recovery mode, ...
> If the target will report a new config it must save the config URL and
> that is not so easy. If the configuration URL is available on every
> request to the "Base Poll Resource" the target can decide if the
> configuration has changed an report if necessary.
> 

I have a different understanding for configData. It is mainly used to
acquire information from the target when the target has never announced
to hawkbit. In fact, the configData URL just disappears when the
confiData are successfully posted by the target.

The logic on the target is to send the configData just if the URL
appears, and do not send it if there is no URL. What you are proposing
remove the stateless condition of the target, and it must known which is
the last configData sent to Hawkbit - this is much more complicate,
because a different software, reboots, etc. can happen on the target.

You should need a "GET configData" to check what is stored in Hawkbit,
but there is not this API.

Regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by EugenWiens** [comment] 2016-12-19 10:33
Hi Stefano,
Ok. That means that the config data can only be static stuff like MAC address or serial-number.

The use case that I have is to give device information to hawkBit that are dynamically
- like software version
- boot loader version
- health status
- hardware version
- ...
This information should used in the roll-out filters. What is the best way to get this dynamic attributes in the roll-out filter?

When hawkBit would add the config Url to every /DEFAULT/controller/v1/<DeviceId> request, the device can be still state loss.

Regards,
Eugen

**Comment by sbabic** [comment] 2016-12-19 11:27
Hi Eugen,

On 19/12/2016 11:33, Eugen Wiens wrote:
> Hi Stefano,
> Ok. That means that the config data can only be static stuff like MAC
> address or serial-number.
> 

As far as I have understood, this is the goal of configData. And Hawkbit
itself just saves the data, but values should be evaluated outside Hawkbit.

> The use case that I have is to give device information to hawkBit that
> are dynamically
> 
>   * like software version
>   * boot loader version
>   * health status
>   * hardware version
>   * ...

I do not see currently in the DDI a way for such dynamic information.

>     This information should used in the roll-out filters. What is the
>     best way to get this dynamic attributes in the roll-out filter?
> 
> When hawkBit would add the config Url to every /DEFAULT/controller/v1/
> request, the device can be still state loss.

If the URL is sent to every  /DEFAULT/controller/v1/ request, the device
should always answer posting its current configData. This increases the
traffic and I know that in some cases this is imporatant - as devices
with just GSM modems and traffic must be paid.

If a configData answer is just sent if something changes, the device is
not anymore stateless.

Best regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by michahirsch** [comment] 2016-12-19 13:05
@sbabic that's correct :+1: .  The configData URL is only showed as long the device has not sent it's properties yet, nevertheless hawkBit will not block for putting more device attributes to the hawkBit server.

These configData can then be used in the rollout-filter exactly. But the configData was intended like static information about HW, like the hardware-revision number e.g. to identify which software needs to be deployed on this hardware.

**Comment by EugenWiens** [comment] 2016-12-19 13:25
@michahirsch Ok.
In my use-case the HW-Revision can change for the same device. e.g. in the service department.

The second use-case is device management. I hoped that the config data can also cover that.

Regards,
Eugen

**Comment by michahirsch** [comment] 2016-12-19 13:32
@EugenWiens  understood. Just for clarification, hawkBit itself is not intended to be a device management, though it's covering part of it because software update is mostly a part in a device management. But hawkBit only focusing on the software update management part and for that there are also some device meta-data necessary for identifying the correct device :)

So the attributes can be used for identifying devices and yes currently hawkBit is not blocking the device in sending more attributes and even sending attributes to the URL even though it's not in the poll-response (links)

**Comment by EugenWiens** [comment] 2016-12-19 13:40
@melanieretter Ok you can close this topic.

**Comment by michahirsch** [comment] 2016-12-19 13:41
Closing it :+1:

**Closed by michahirsch** 2016-12-19 13:41 UTC
Labels: question
